name: experiments

on:
  workflow_dispatch:
    inputs:
      production:
        required: true
        type: boolean    
      flag1:
        required: true
        type: boolean    
      flag2:
        required: true
        type: boolean    
      username:
        description: 'A username passed from the caller workflow'
        default: 'john-doe'
        required: false
        type: string
        
env:
  production: ${{ github.event.inputs.production }}  
  flag1: ${{ github.event.inputs.flag1 }}
  flag2: ${{ github.event.inputs.flag2 }}
  username: ${{ github.event.inputs.username }}

jobs:
  contexts:
    runs-on: ubuntu-latest
    steps:
      - run: |
          pwd
          echo production ${{ env.production }}
          echo env.flag1 ${{ env.flag1 }}
          echo env.flag2 ${{ env.flag2 }}
          echo env.username ${{ env.username }}
          
          echo inputs.production ${{ inputs.production }}
          echo inputs.flag1 ${{ inputs.flag1 }}
          echo inputs.flag2 ${{ inputs.flag2 }}
          echo inputs.username ${{ inputs.username }}
          
          
          echo github.event.inputs.production ${{ github.event.inputs.production }}
          echo github.event.inputs.flag1 ${{ github.event.inputs.flag1 }}
          echo github.event.inputs.flag2 ${{ github.event.inputs.flag2 }}
          echo github.event.inputs.username ${{ github.event.inputs.username }}
          
          
          if [ ${{ env.production }} ]; then
            echo 1-production...
            echo 1-PRODUCTION
            echo 1-PRODUCTION
          else
            echo 1-develop...
            echo 1-DEVELOP
            echo 1-DEVELOP
          fi          


          if [ ${{ env.production }} ]; then
            echo 2-production...
            echo 2-PRODUCTION
            echo 2-PRODUCTION
          else
            echo 2-develop...
            echo 2-DEVELOP
            echo 2-DEVELOP
          fi      
          
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: |
          pwd

          echo production ${{ env.production }}
          echo env.flag1 ${{ env.flag1 }}
          echo env.flag2 ${{ env.flag2 }}
          echo inputs.production ${{ inputs.production }}
          echo inputs.flag1 ${{ inputs.flag1 }}
          echo inputs.flag2 ${{ inputs.flag2 }}
          echo env.production == true: ${{ env.production == true }}
          
          if [ ${{ env.production }} ]; then
            echo 1-production...
            echo 1-PRODUCTION
            echo 1-PRODUCTION
          else
            echo 1-develop...
            echo 1-DEVELOP
            echo 1-DEVELOP
          fi          


          if [ ${{ env.production }} ]; then
            echo 2-production...
            echo 2-PRODUCTION
            echo 2-PRODUCTION
          else
            echo 2-develop...
            echo 2-DEVELOP
            echo 2-DEVELOP
          fi      

          function func_export_ipa {
            echo func_export_ipa $1 $2
          }            

          if [ ${{ env.production }} ]; then
            echo production...
            func_export_ipa "../../exportOptionsAppStore.plist" ApprovalMax_AppStore_.ipa
            func_export_ipa "../../exportOptionsAdHoc.plist" ApprovalMax_AdHoc_.ipa
          else
            echo develop...
            func_export_ipa "../../exportOptionsAmaxdevAdHoc.plist" ApprovalMax_develop_adHoc_.ipa
          fi          
          echo completed...
          
          
          
